// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsL4JdtcyCLuM7285QVctqI3f9SaAg9bU',
    appId: '1:1004559604026:web:c2e75f5f213cb6673bd803',
    messagingSenderId: '1004559604026',
    projectId: 'tamagotchi-tamer',
    authDomain: 'tamagotchi-tamer.firebaseapp.com',
    storageBucket: 'tamagotchi-tamer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkyv1gHGfRFUgfFqxwTqf5B5m1qLy6fQ',
    appId: '1:1004559604026:android:3a5023e8ed0bd9b93bd803',
    messagingSenderId: '1004559604026',
    projectId: 'tamagotchi-tamer',
    storageBucket: 'tamagotchi-tamer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7P2n8vPmGVWTOWplYy1FaQJr0IoA4Mk',
    appId: '1:1004559604026:ios:de31788266ca2b503bd803',
    messagingSenderId: '1004559604026',
    projectId: 'tamagotchi-tamer',
    storageBucket: 'tamagotchi-tamer.appspot.com',
    iosBundleId: 'com.example.tamagotchiTamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM7P2n8vPmGVWTOWplYy1FaQJr0IoA4Mk',
    appId: '1:1004559604026:ios:8005361e5ea448d23bd803',
    messagingSenderId: '1004559604026',
    projectId: 'tamagotchi-tamer',
    storageBucket: 'tamagotchi-tamer.appspot.com',
    iosBundleId: 'com.example.tamagotchiTamer.RunnerTests',
  );
}
